### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by ceckoslab** [nicjansma/puppetarazzi#1]
Hello @nicjansma 

Thanks for the great product your are developing. I am right now starting experimenting with puppetarazzi and most likely will create docker container where I would run it in isolation. My motivation is that I come from PHP world and I always have troubles setting up NPM locally but when I isolate the wholes story in Docker container then all works just fine.

My motivation:

- Easy onboarding for people who just want to try it out but don't have their local machine in order
- Possibility to run puppetarazzi somewhere in the cloud for short time, collect needed data and then stop it. It may be cost efficient usage.

I will try to create such docker setup and contribute back. 

Your thoughts?

**Comment by nicjansma** [comment]
@ceckoslab that's a really good idea!  I'm glad you're using the tool.  It'd be fantastic to have a portable docker image to run in the cloud too.

Have you had a chance to build any images yet?

**Comment by ceckoslab** [comment]
Hello @nicjansma 

Still trying and it looks almost done. Seems that I will need to build custom image and run the process from specific user in order to satisfy some permissions for puppeteer.

```
const browser = await puppeteer.launch({
  executablePath: '/usr/bin/chromium-browser'
});
```

Still trying :)

**Comment by ceckoslab** [comment]
Hello @nicjansma 

I managed to build locally puppetarazzi based on https://hub.docker.com/r/alekzonder/puppeteer/

There is only one problem that I believe I can't do on my own. In order to run it inside the container I needed to modify a bit src/puppetarazzi.js

I changed:
```
let browser = await puppeteer.launch();
```

To:
```
let browser = await puppeteer.launch({
                args: [
                    '--no-sandbox',
                    '--disable-setuid-sandbox'
                ]
            }
        );
```

Do you think that you can add 3rd argument for puppetarazzi which if exist allows us to pass the parameters above to puppeteer.launch()?

Example parameter name could be **dockerized**.

So far it looks very good and it works for me for. I am not sure what should be the right approach from best Docker practices because I can build puppetarazzi image or use similar command that just mounts puppetarazzi inside puppeteer container and runs all the audits:
```
docker run --shm-size 1G --rm -v <path_to_script>:/app/index.js alekzonder/puppeteer:latest
```

Anyway I will continue experimenting but please let me know if you are willing to apply the small change I mentioned in this comment .

Have a nice day!

**Comment by nicjansma** [comment]
Great work @ceckoslab !  I've added an option to the JSON file for `puppeteerOptions`, where you should be able to use the above.  Does this work for you?

https://github.com/nicjansma/puppetarazzi/commit/195c4d5d68b50e329b0abf06286276df94f1ed10
